######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 26 12:16:47 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += profile_widget.h
SOURCES += main.cpp profile_widget.cpp
