######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 9 15:54:48 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main_window.h
SOURCES += main.cpp main_window.cpp
