######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 26 12:11:29 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
