######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 26 12:05:04 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
